#server:
#  port: 8989
#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/sg_blog?characterEncoding=utf-8&serverTimezone=UTC
#    username: root
#    password: hy20030123
#    driver-class-name: com.mysql.cj.jdbc.Driver
#
#  servlet:
#    # 文件上传
#    multipart:
#      # 单个上传文件的最大允许大小
#      max-file-size: 20MB
#      # HTTP请求中包含的所有文件的总大小的最大允许值
#      max-request-size: 20MB
#
#mybatis-plus:
#  configuration:
#    # 日志
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#  global-config:
#    db-config:
#      logic-delete-field: delFlag
#      logic-delete-value: 1
#      logic-not-delete-value: 0
#      id-type: auto
#
## 打开七牛云，找到密钥管理，把相关信息填写到下面3行，会被huanf-blog工程的OOSTest类获取
#myoss:
#  accessKey: _ibGP9wytjLCAZPqcFaWQNxbw7fMUvofSOvOFFR3
#  secretKey: QSOAU-cv3sSDGNfVNPF6iXz-PsP5X9QTrjFI9zYw
#  bucket: huanf-blog



server:
  port: 8989

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sg_blog?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: hy20030123
    driver-class-name: com.mysql.cj.jdbc.Driver

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

  mvc:
    charset: UTF-8
    locale: zh_CN
    locale-resolver: fixed

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: delFlag
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: auto

myoss:
  access-key: ${OSS_ACCESS_KEY}
  secret-key: ${OSS_SECRET_KEY}
  bucket: huanf-blog
